### ISSUE TITLE
Convert utility methods to a SciJava standard

### ISSUE THREAD

**Issue by hinerm** [tferr/Scripts#14]
The idea of per-script language utility methods is something we should standardize, so that the SciJava framework handles a lot of the basic stuff (e.g. discovering and printing available commands).

The issue for generalizing this is in [SciJava](https://github.com/scijava/scijava-common/issues/186) but I think BAR would be a great use case to drive this work, so it would be great to develop this together.

**Comment by hinerm** [comment]
@tferr This could be a fun thing to work on together for your time at the hackathon!

**Comment by tferr** [comment]
Not so sure if I'm up to it, but definitely yes!

**Comment by tferr** [comment]
This is now implemented as an "external Op". Discussed in #16
