### ISSUE TITLE
Scientific representation of y values in Find Peaks (1e-4 instead of 0.0004)

### ISSUE THREAD

**Issue by roedel02** [tferr/Scripts#20]
Hi!
I just installed BAR to use the "Find_Peaks" tool ( Scripts/BAR/src/main/resources/scripts/BAR/Data_Analysis/Find_Peaks.bsh ). Thanks for developing it, it's very useful!
I'm new on github, sorry if I chose the wrong place to report an error.
Is it possible to return the result of the peak finder in a scientific representation (1e-4 instead of 0.0004)? I'm working with a 32bit tif image with float values between -2e-12 and +1e-8. The program finds all maxima and minima as needed and returns the plot results in a table "Plot Values". The minimum y-values are fine (e.g. -1.05732E-11), but the y-values of the maxima are displayed as a float (e.g. 0.000000007). Better accuracy would be helpful.
Thanks!

**Comment by tferr** [comment]
Even if not documented that feature exists already:
Please toggle _scientific notation_ in _Analyze>Set Measurements..._ then run _Find Peaks_. Does it work for you?

**Comment by roedel02** [comment]
Oh, that was an easy fix. Sorry for bothering you and thanks a lot for the fast answer!

**Comment by tferr** [comment]
No problem, it is one of those things: easier to implement than to document. I just added a mention to the [wiki page](http://imagej.net/Find_Peaks#Notes), so it is not forgotten. As per where to submit issues like this: here is great, the [ImageJ forum](http://forum.imagej.net) also works.
